### ISSUE TITLE
Missing placement/population in output JSON

### ISSUE THREAD

**Issue by feesta** [migurski/Dymo#2]
population and placement (NE,SW,etc) are not included in the label output JSON.

**Comment by migurski** [comment]
Fixed in 5cc72ce2

**Comment by feesta** [comment]
Thanks for adding the properties. The placement is still not coming through.

**Comment by nvkelso** [comment]
Fixed in https://github.com/migurski/Dymo/issues/8
